Spring boot 3 upgrade (#2584)
* Update javax to jakarta namespace

* Update javax to jakarta namespace

* Update feign client to v5

* Update javax to jakarta namespace

* Update spring security configuration

* Update status code to be three digits

* Move suppressions as per rse-gradle-java-plugin docs

* Spring boot 3 upgrade and dependency rollup

* Update tests to use arrays rather than lists

* Remove trailing slash as part of spring boot 3 upgrade

* Remove unused files

* Update dependencies

* Update to java 21

* Update tests to junit 5

* Update suppressions

* Update suppressions

* Update getFileSystemResource to catch null pointer exceptions

* Exclude spring security default password

* Update dependencies

* Update tests

* Update security configuration to remove warnings

* Remove .vscode directory

* Update jackson version

* Update test to junit 5

* Rollback security configuration

* rollback jacksonDatabind from 2.17.1 to 2.14.3

* fix DocumentServiceTest.java unit test issue

* fix DocumentServiceTest.java unit test issue

* fix DocumentServiceTest.java unit test issue

* fix unit tests issue

* suppress CVE for jackson Databind 2.15.3

* fix style issue

* fix functional tests style issue

* rollback jackson Databind to 2.14.3

* fix integration tests NoSuchMethodError

* fix integration tests

* fix integration tests style issue

* fix integration tests

* temp disable LifeEventCCDIntegrationIT

* temp exclude SecurityConfiguration.java from sonar

* exclude SecurityConfiguration.java from sonar

* Remove this redundant "@Qualifier" annotation and rely on the @Bean method.

* exclude BusinessRulesValidationApplication.java &  AuthCheckerConfiguration.java from sonar

* exclude BusinessRulesValidationApplication.java,& AuthCheckerConfiguration.java from sonar

* add ResponseEntityDecoder

* fix SidamExchangeCodeConsumerTest

* rollback temp fix changes

* fix jackson bind for legalStatemen DocumentType issue

* delete no use import at LifeEventCCDIntegrationIT.java

* fix Integration Exception error

* fix Integration test on LifeEventCCDIntegrationIT.java

* update terraform-version to 1.8.5

* fix SmokeTests error

* update @Ignore to @Disabled on tests

* fix commonsValidator typo

* fix Dockerfile typo

* try downgrade from java 17 to 21

* try downgrade from java 17 to 21

* add a debug log to PaymentsService.java

* add a debug log to DocumentManagementServiceImpl.java

* update ScheduledNotificationsTests from @pending to @Disabled

* add PaymentServiceResponse.java fix jackson databind issue

* add debug message to generate Grant functional test

* add debug message EventValidationService.java

* upgrade documentClient to 7.0.1

* rollback documentClient to 1.7.3

* rollback documentClient to 1.7.3

* implement a new DocumentManagement Feign  client

* fix IT test with a new DocumentManagement Feign  client

* add debug log to getDocumentByBinaryUrl

* rollback new DocumentManagementClient.java client

* Updating Terraform Formatting

* update documentClient to version 1.8.0.8

* update documentClient to version 1.8.0.11

* update documentClient to version Major 1.8.1

* rollback debug message

* fix sonar to Remove this redundant "@Qualifier" annotation and rely on the @Bean method

* rollback Remove this redundant "@Qualifier" annotation and rely on the @Bean method

* fix unit test issue with ExceptionRecordCaseDataValidatorTest.java

* DTSPB-3430 update probate commons version

* update azure-storage-blob' to version: '12.27.1'

* suppress CVE-2023-36052

* update lev client version

* exclude all commons-logging for fortify scan

* fix fortify scan

---------

Co-authored-by: MarcusHMCTS <Marcus.Ho@justice.gov.uk>
Co-authored-by: Marcus Ho <99657446+MarcusHMCTS@users.noreply.github.com>
Co-authored-by: FeliTam <feli.tam@justice.gov.uk>
Co-authored-by: 54687 <61242337+hmcts-jenkins-j-to-z[bot]@users.noreply.github.com>